[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
sample_program = "GWKBYXfT5EMPa6avVVk3J7xTZJi3AY6cNQtQXHRfJaXZ"

[registry]
url = "https://api.apr.dev"

# [provider]
# cluster = "Localnet"
# wallet = "~/.config/solana/id.json"

[provider]
cluster = "Devnet"
wallet = "./sample-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
